{
    "openapi": "3.0.1",
    "info": {
        "title": "API feita com Node.js",
        "description": "Desafio 3 do curso de Node.js da Rocketseat",
        "contact": {
            "name": "Juliano J. S. Tavares",
            "url": "https://linkedin.com/in/julianojstavares"
        },
        "version": "0.1"
    },
    "servers": [
        {
            "url": "http://localhost:3333"
        }
    ],
    "paths": {
        "/users": {
            "get": {
                "description": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "string"
                                },
                                "examples": {
                                    "example 1": {
                                        "value": [
                                            {
                                                "id": "a5574a95-d87a-4bc1-996a-d6ed8ccba266",
                                                "admin": true,
                                                "name": "John Doe",
                                                "email": "john@doe.com",
                                                "created_at": "2022-08-05T20:37:07.033Z",
                                                "updated_at": "2022-08-05T20:37:07.033Z"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "http://localhost:3333"
                    }
                ]
            },
            "servers": [
                {
                    "url": "http://localhost:3333"
                }
            ]
        },
        "/users/{user_id}": {
            "get": {
                "description": "Get user by id",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "header",
                        "required": false,
                        "style": "simple",
                        "explode": false,
                        "schema": {
                            "type": "string"
                        },
                        "example": "2f4890d7-293c-4920-b374-bd363bf6ca48"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "string"
                                },
                                "examples": {
                                    "example 1": {
                                        "value": {
                                            "id": "a5574a95-d87a-4bc1-996a-d6ed8ccba266",
                                            "admin": false,
                                            "name": "John Doe",
                                            "email": "john@doe.com",
                                            "created_at": "2022-08-05T20:37:07.033Z",
                                            "updated_at": "2022-08-05T20:37:07.033Z"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "string"
                                },
                                "examples": {}
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "http://localhost:3333"
                    }
                ]
            },
            "servers": [
                {
                    "url": "http://localhost:3333"
                }
            ]
        },
        "/users/": {
            "post": {
                "description": "Create user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/users_body"
                            },
                            "examples": {
                                "exaple 1": {
                                    "value": "{\r\n\t\"name\": \"John Doe\",\r\n\t\"email\": \"john@doe.com\"}"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "string"
                                },
                                "examples": {
                                    "example 1": {
                                        "value": {
                                            "id": "a5574a95-d87a-4bc1-996a-d6ed8ccba266",
                                            "admin": false,
                                            "name": "John Doe",
                                            "email": "john@doe.com",
                                            "created_at": "2022-08-05T20:37:07.033Z",
                                            "updated_at": "2022-08-05T20:37:07.033Z"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "http://localhost:3333"
                    }
                ]
            },
            "servers": [
                {
                    "url": "http://localhost:3333"
                }
            ]
        },
        "/users/{user_id}/admin": {
            "patch": {
                "description": "Set user as administrator",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/users_{user_id}_admin"
                            },
                            "examples": {
                                "example 1": {
                                    "value": "{\r\n\t\"name\": \"John Doe\",\r\n\t\"email\": \"john@doe.com\"}"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json; charset=utf-8": {
                                "schema": {
                                    "type": "string"
                                },
                                "examples": {
                                    "example 1": {
                                        "value": {
                                            "id": "a5574a95-d87a-4bc1-996a-d6ed8ccba266",
                                            "admin": true,
                                            "name": "John Doe",
                                            "email": "john@doe.com",
                                            "created_at": "2022-08-05T20:37:07.033Z",
                                            "updated_at": "2022-08-05T20:37:07.033Z"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "servers": [
                    {
                        "url": "http://localhost:3333"
                    }
                ]
            },
            "servers": [
                {
                    "url": "http://localhost:3333"
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "users_body": {
                "type": "object",
                "properties": {
                    "updated_at": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    }
                }
            },
            "users_{user_id}_admin": {
                "type": "object",
                "properties": {
                    "updated_at": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    }
                }
            }
        }
    }
}